<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>设置我的资料</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div class="x-nav">
        <span class="layui-breadcrumb">
            <a href="javascript:">用户</a> <a><cite>信息</cite></a>
        </span>
    <a class="layui-btn layui-btn-sm" style="margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh"></i>
    </a>
</div>
<div class="x-body">
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-card">
                <div class="layui-card-header">账户信息</div>
                <table class="layui-table">
                    <thead>
                    <tr>
                        <th colspan="2" scope="col">个人资料</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th width="30%">注册日期</th>
                        <td><span id="lbServerName">2019-5-3</span></td>
                    </tr>
                    <tr>
                        <th width="30%">结算周期</th>
                        <td><span id="lbServerName">T+1</span></td>
                    </tr>
                    <tr>
                        <th width="30%">Email</th>
                        <td><span id="lbServerName">xxx@gmail.com</span></td>
                    </tr>
                    <tr>
                        <td>手机号码</td>
                        <td>13800138000</td>
                    </tr>
                    <tr>
                        <td>QQ</td>
                        <td>123456</td>
                    </tr>
                    </tbody>
                </table>
                <table class="layui-table" lay-even>
                    <thead>
                    <tr>
                        <th>产品ID</th>
                        <th>产品名称</th>
                        <th>费率</th>
                        <th>状态</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>总数</td>
                        <td>92</td>
                        <td>8</td>
                        <td>20</td>
                    </tr>
                    <tr>
                        <td>今日</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="/static/layui/layui.js"></script>
<script>
	layui.use(['jquery', 'form', 'layer', 'element'], function () {
		var element = layui.element, $ = layui.jquery
	})
</script>
</body>
</html>