<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>收付款IP设置</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div class="x-nav">
        <span class="layui-breadcrumb">
            <a href="javascript:">用户</a> <a><cite>IP限制</cite></a>
        </span>
    <a class="layui-btn layui-btn-sm" style="margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh"></i>
    </a>
</div>
<div class="x-body">
    <blockquote class="layui-elem-quote">为了你的资金安全, 将限制你的充值与代付IP地址<br><br>关闭后一天充值或代付不能超过10笔, 每笔不能超过50元<br><br>关闭仅作为开发或测试期间使用.开启后无限制</blockquote>
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">IP限制设置</div>
                <div class="layui-card-body" pad15>
                    <form class="layui-form">
                        <div class="layui-form-item">
                            <label class="layui-form-label">限制开关: </label>
                            <div class="layui-input-inline">
                                <input type="checkbox" name="state" lay-skin="switch" lay-text="ON|OFF">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">IP地址: </label>
                            <div class="layui-input-inline">
                                <textarea name="ip_addr" autocomplete="off" class="layui-textarea" placeholder="一行一个IP, 最多3个"></textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux">一行一个IP,最多3个</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">邮箱验证码: </label>
                            <div class="layui-input-inline">
                                <input class="layui-input" type="number" name="mail_captcha" lay-verify="required" autocomplete="off" id="vercode">
                            </div>
                            <div class="layui-input-inline">
                                <button class="layui-btn" id="xcaptcha">获取验证码</button>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">OTP校验码: </label>
                            <div class="layui-input-inline">
                                <input type="text" name="otp_code" lay-verify="required" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="xForm">确认修改</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/static/layui/layui.js"></script>
<script>
	layui.use(['jquery', 'form', 'layer', 'element'], function () {
		var element = layui.element, $ = layui.jquery, form = layui.form;
		//发送验证码
		$('#xcaptcha').click(sendcode = function () {
			var sec              = 120,
			    btn              = $(this),
				token = null,
				timer, countDown = function (loop) {
				sec--;
				if (sec < 0) {
					btn.removeClass('layui-disabled').html('获取验证码');
					btn.bind('click', sendcode);
					sec = 180;
					clearInterval(timer)
				} else {
					btn.addClass('layui-disabled').html(sec + '秒后重获');
					btn.unbind('click')
				}
				if (!loop) {
					timer = setInterval(function () {countDown(true)}, 1000)
				}
			};
			countDown();
			$.ajax({
				type    : 'POST',
				url     : '/user/captcha',
				dataType: 'json',
				success : function (res) {
					res.code === 0 ? layer.msg('验证码已发送至你的邮箱', { icon: 1, shade: 0 }) : layer.msg('未知错误', { icon: 2, shade: 0 })
				},
				error   : function (err) {
					err.responseJSON ? layer.msg(err.responseJSON.msg, { icon: 2, shade: 0 }) : layer.msg('未知错误', { icon: 2, shade: 0 })
					sec = 0
				}
			});
            return false;
		});
		form.on('submit(xForm)', function (rawData) {
			// if (sec > 0) {
			// 	layer.msg('验证码超时, 请先获取验证码', { icon: 2, shade: 0 })
			// 	return false
			// }
			$.ajax({
				url     : '/user/ip',
				method  : 'POST',
				dataType: 'JSON',
				data    : rawData.field,
				success : function (res) {
					res.code === 0 ? layer.msg('修改IP设置成功', { icon: 1, shade: 0 }) : layer.msg('未知错误', { icon: 2, shade: 0 })
				},
				error   : function (err) {
					err.responseJSON ? layer.msg(err.responseJSON.msg, { icon: 2, shade: 0 }) : layer.msg('未知错误', { icon: 2, shade: 0 })
				}
			});
			return false//如果不加这句，则ajax的回调函数不执行
		})
	})
</script>

</body>
</html>
