<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>操作记录</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/style.css">

</head>

<body>
<div class="x-nav">
        <span class="layui-breadcrumb">
            <a href="javascript:">用户</a> <a><cite>操作日志</cite></a>
        </span>
    <a class="layui-btn layui-btn-sm" style="margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh"></i>
    </a>
</div>
<div class="x-body">
    <blockquote class="layui-elem-quote">保留30天内网页端的操作记录</blockquote>
    <!-- table -->
    <div class="table-scroll">
        <table id="tableId" class="layui-hide"></table>
    </div>
    <script type="text/html" id="buttonTpl">
        {{#  if(d.state == 1){ }}
        <span class="layui-badge layui-bg-green"> 开启 </span>
        {{#  } else { }}
        <span class="layui-badge layui-bg-red"> 关闭 </span>
        {{#  } }}
    </script>
    <script type="text/html" id="barDemo">
        <a title="编辑" lay-event="edit" href="javascript:"> <i class="layui-icon layui-icon-edit"></i> </a>
        <a title="删除" lay-event="del" href="javascript:"> <i class="layui-icon layui-icon-delete"></i> </a>
    </script>
</div>
<script src="/static/layui/layui.js"></script>
<script src="/static/js/admin.js"></script>
<script>
	// 面包屑需要依赖`element`模块
	// 页面调用xShow()打开<iframe/>
	layui.use(['table', 'jquery', 'form', 'layer', 'element', 'laydate'], function () {
		var table = layui.table, $ = layui.jquery, form = layui.form, element = layui.element, layer = layui.layer, laydate = layui.laydate

		renderTable(null); // 初始化没渲染表格

		// 表格渲染
		function renderTable (dateField) {
			table.render({
				elem  : '#tableId',
				method: 'post',
				url   : '/user/op',
				where : dateField,
				// 分页
				page  : { //支持传入 laypage 组件的所有参数（某些参数除外，如：jump/elem） - 详见文档
					layout: ['limit', 'count', 'prev', 'page', 'next', 'skip'], //自定义分页布局
					groups: 3,      //显示连续页码数
					first : '首页', //不显示首页
					last  : '末页', //不显示尾页
				},
				limits: [25, 50, 100],
				limit : 25, //每页默认显示的数量
				cols  : [
					[
						{ field: 'uid', title: '商户号', minWidth: 90, align: 'center' }
						, { field: 'act_type', title: '操作类型', minWidth: 90, align: 'center' }
						, { field: 'act_desc', title: '操作描述', minWidth: 90, align: 'center' }
						, { field: 'ctime', title: '操作时间', minWidth: 90, align: 'center' }
						, { field: 'ip_addr', title: 'IP', minWidth: 90, align: 'center' }
					],
				],
			})
		}
	})
</script>
</body>

</html>