<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>修改登录密码</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div class="x-nav">
        <span class="layui-breadcrumb">
            <a href="javascript:">用户</a> <a><cite>修改登录密码</cite></a>
        </span>
    <a class="layui-btn layui-btn-sm" style="margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh"></i>
    </a>
</div>
<div class="x-body">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">登录密码修改</div>
                <div class="layui-card-body" pad15>

                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">当前密码: </label>
                            <div class="layui-input-inline">
                                <input type="password" name="oldPassword" lay-verify="required" lay-verType="tips" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">新密码: </label>
                            <div class="layui-input-inline">
                                <input type="password" name="password" lay-verify="pass" lay-verType="tips" autocomplete="off" id="LAY_password" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux">6到16个字符</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">确认新密码: </label>
                            <div class="layui-input-inline">
                                <input type="password" name="repassword" lay-verify="repass" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="xForm">确认修改</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/static/layui/layui.js"></script>
<script>
	layui.use(['jquery', 'form', 'layer', 'element'], function () {
		var element = layui.element, $ = layui.jquery,form = layui.form;

        form.on('submit(xForm)', function (rawData) {
            $.ajax({
                url     : '/user/password',
                method  : 'POST',
                dataType: 'JSON',
                data    : rawData.field,
                success : function (res) {
                    res.code === 0 ? layer.msg('修改IP设置成功', { icon: 1, shade: 0 }) : layer.msg('未知错误', { icon: 2, shade: 0 })
                },
                error   : function (err) {
                    err.responseJSON ? layer.msg(err.responseJSON.msg, { icon: 2, shade: 0 }) : layer.msg('未知错误', { icon: 2, shade: 0 })
                }
            });
            return false//如果不加这句，则ajax的回调函数不执行
        })
	})
</script>

</body>
</html>