<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>订单管理</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/style.css">

</head>

<body>
<div class="x-nav">
        <span class="layui-breadcrumb">
            <a href="javascript:">首页</a> <a><cite>入款中订单</cite></a>
        </span>
    <a class="layui-btn layui-btn-sm" style="margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh"></i>
    </a>
</div>
<div class="x-body">
    <!-- search -->
    <form class="layui-form we-search" method="POST">
        <div class="layui-input-inline btn-dropdown">
            <select lay-filter="selectCondition"">
            <option value="tx_no">平台单号</option>
            <option value="tx_out_no">商户单号</option>
            </select>
            <input id="condition" type="text" name="tx_no" lay-verify="title" autocomplete="off" placeholder="请输入" class="layui-input">
        </div>
        <div class="layui-input-inline w100px">
            <select name="prod_id">
                <option value="">全部通道</option>
                <option value="0">网银网关</option>
                <option value="1">银联快捷</option>
                <option value="1">银联扫码</option>
                <option value="1">支付宝H5</option>
                <option value="1">支付宝扫码</option>
            </select>
        </div>
        <div class="layui-input-inline w100px">
            <select name="state">
                <option value="">订单状态</option>
                <option value="0">处理中</option>
                <option value="1">处理成功</option>
                <option value="2">超时失败</option>
                <option value="2">通道失败</option>
            </select>
        </div>
        <div class="layui-input-inline">
            <input type="text" name="ctime_bucket" class="layui-input w300px ctime_bucket" placeholder="下单时间">
        </div>
        <div class="layui-input-inline">
            <input type="text" name="etime_bucket" class="layui-input w300px etime_bucket" placeholder="处理时间">
        </div>
        <div class="layui-input-inline">
            <button class="layui-btn" lay-submit lay-filter="searchForm"><i class="layui-icon">&#xe615;</i></button>
        </div>
    </form>
    <!-- table -->
    <div class="table-scroll">
        <table id="tableId" class="layui-hide"></table>
    </div>
    <script type="text/html" id="buttonTpl">
        {{#  if(d.state == 1){ }}
        <span class="layui-badge layui-bg-green"> 开启 </span>
        {{#  } else { }}
        <span class="layui-badge layui-bg-red"> 关闭 </span>
        {{#  } }}
    </script>
    <script type="text/html" id="barDemo">
        <a title="编辑" lay-event="edit" href="javascript:"> <i class="layui-icon layui-icon-edit"></i> </a>
        <a title="删除" lay-event="del" href="javascript:"> <i class="layui-icon layui-icon-delete"></i> </a>
    </script>
</div>
<script src="/static/layui/layui.js"></script>
<script src="/static/js/admin.js"></script>
<script>
	// 面包屑需要依赖`element`模块
	// 页面调用xShow()打开<iframe/>
	layui.use(['table', 'jquery', 'form', 'layer', 'element', 'laydate'], function () {
		var table = layui.table, $ = layui.jquery, form = layui.form, element = layui.element, layer = layui.layer, laydate = layui.laydate

		form.on('submit(searchForm)', function (data) {renderTable(data.field);return false;}) // 提交表单数据
		form.on('select(selectCondition)', function (data) {$('#condition').attr('name', data.value)}) // 根据选择类型, 更改输入框name

		// 时间渲染
		laydate.render({ elem: '.ctime_bucket', type: 'datetime', range: '|', format: 'y-MM-dd HH:mm:ss' })
		laydate.render({ elem: '.etime_bucket', type: 'datetime', range: '|', format: 'y-MM-dd HH:mm:ss' })

		renderTable(null) // 初始化没渲染表格

		// 表格渲染
		function renderTable (dateField) {
			table.render({
				elem  : '#tableId',
				method: 'post',
				url   : '/tx/paying',
				where : dateField,
				// 分页
				page  : { //支持传入 laypage 组件的所有参数（某些参数除外，如：jump/elem） - 详见文档
					layout: ['limit', 'count', 'prev', 'page', 'next', 'skip'], //自定义分页布局
					groups: 3,      //显示连续页码数
					first : '首页', //不显示首页
					last  : '末页', //不显示尾页
				},
				limits: [25, 50, 100],
				limit : 25, //每页默认显示的数量
				cols  : [
					[
						{ field: 'tx_no', title: '订单号', minWidth: 90, align: 'center' }
						, { field: 'tx_out_no', title: '商户单号', minWidth: 90, align: 'center' }
						, { field: 'prod_id', title: '产品类型', minWidth: 90, align: 'center' }
						, { field: 'amt_all', title: '总金额', minWidth: 90, align: 'center' }
						, { field: 'amt_rec', title: '到账金额', minWidth: 90, align: 'center' }
						, { field: 'fee_all', title: '手续费', minWidth: 90, align: 'center' }
						, { field: 'state', title: '处理状态', minWidth: 80, align: 'center' }
						, { field: 'state', title: '结算状态', minWidth: 80, align: 'center' }
						, { field: 'ctime', title: '创建时间', minWidth: 100, align: 'center' }
						, { field: 'mtime', title: '处理时间', minWidth: 100, align: 'center' }
						, { field: 'ip_addr', title: 'IP地址', minWidth: 100, align: 'center' }
					],
				],
			})
		}
	})
</script>
</body>

</html>