<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>404</title>
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<link rel="stylesheet" href="/static/css/font.css">
	<link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div class="x-body">
	<div class="x-trailer">
		404 Not Found
	</div>
</div>
</body>
</html>