<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<button onclick="Ajax()">哈哈</button>
</body>
</html>

<script>
	function Ajax () {
		var ajax                = new XMLHttpRequest()
		ajax.onreadystatechange = function () {
			this.response = JSON.parse(this.responseText)
			if (this.readyState == 4 && this.status == 200) {
				document.getElementById('demo').innerHTML = this.responseText
			}else{

            }
		}
		ajax.open('POST', '/index/test', true)
		ajax.send()
	}

	function Ajax2(type, url, data, success, failed){
		// 创建ajax对象
		var xhr = new XMLHttpRequest();
		var type = type.toUpperCase();
		// 用于清除缓存
		var random = Math.random();

		if(typeof data == 'object'){
			var str = '';
			for(var key in data){
				str += key+'='+data[key]+'&';
			}
			data = str.replace(/&$/, '');
		}

		if(type == 'GET'){
			if(data){
				xhr.open('GET', url + '?' + data, true);
			} else {
				xhr.open('GET', url + '?t=' + random, true);
			}
			xhr.send();

		} else if(type == 'POST'){
			xhr.open('POST', url, true);
			// 如果需要像 html 表单那样 POST 数据，请使用 setRequestHeader() 来添加 http 头。
			xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
			xhr.send(data);
		} else if()

		// 处理返回数据
		xhr.onreadystatechange = function(){
			if(xhr.readyState == 4){
				if(xhr.status == 200){
					success(xhr.responseText);
				} else {
					if(failed){
						failed(xhr.status);
					}
				}
			}
		}
	}



	function ExportWord () {
		// 要传递的值，这里做个简单示例，实际开发中根据情况取值
		var ids      = 'value'
		// 请求的url
		var url      = '/StudentInfo/ExportWord'
		// 创造一个Dom元素,这里是表单
		var turnForm = document.createElement('form')
		// 将表单加入body中 一定要加入到body中！！
		document.body.appendChild(turnForm)
		//请求方式 默认为post
		var method      = ids['methond'] || 'POST'
		turnForm.method = method
		// 弹出新窗口
		turnForm.target = '_blank'
		// 请求地址
		turnForm.action = url
		// 创建表单元素，用来存储值，传递给后台。这里创建的隐藏域。
		var newElement  = document.createElement('input')
		newElement.setAttribute('type', 'hidden')
		// 设置Name属性
		newElement.setAttribute('name', 'ids')
		// 将创造的隐藏域添加到Form中
		turnForm.appendChild(newElement)
		newElement.setAttribute('value', ids)// 赋值

		// 提交表单
		turnForm.submit()
	}

	function makeForm (url, method, dataField) {
		var target = '_self' //_blank 新窗口中打开, _self默认,在相同的框架中打开。_parent 在父框架集中打开,_top在整个窗口中打开
		// 创建一个 form
		var xform  = document.createElement('form')
		xform.id   = 'form_id'
		xform.name = 'xform'
		// 添加到 body 中
		document.body.appendChild(xform)
		// xform.setAttribute("style","display:none;") // 隐藏表单
		// 创建一个输入框
		var inputForm  = document.createElement('input')
		// 设置相应参数
		inputForm.type = 'text'
		inputForm.name = 'username'
		inputForm.setAttribute('value', 'zhangsan')
		// inputForm.value = 'zhangsan'
		// 将该输入框插入到 form 中
		xform.appendChild(inputForm)
		// form 提交方式
		xform.method = method
		// form 提交路径
		xform.action = url
		// 执行提交
		// xform.submit()
		// 删除该 form
		// document.body.removeChild(form)
	}
</script>
<script>

</script>