<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
	<title>商户后台</title>
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<!-- 顶部开始 -->
<div class="container layui-bg-cyan">
    <div class="logo"> <a _href="./pages/welcome.html" lay-title="<i class='layui-icon layui-icon-home'></i>">XPay</a> </div>
    <div class="left_open"> <i title="展开左侧栏" class="iconfont">&#xe699;</i> </div>

    <ul class="layui-nav right" lay-filter="">
       <li class="layui-nav-item">
            <a href="javascript:;"><i class="layui-icon layui-icon-friends"></i></a>
            <dl class="layui-nav-child r0">
                <!-- 二级菜单 -->
                <dd> <a href="javascript:;"><i class="layui-icon layui-icon-rmb"></i>余额: 3000000.00</a> </dd>
                <dd> <a href="javascript:;"><i class="layui-icon layui-icon-snowflake"></i>冻结: 3000000.00</a> </dd>
                <hr class="margin0">
                <dd> <a onclick="xShow('账户信息','/account/profiles')"><i class="layui-icon layui-icon-username"></i>账户信息</a> </dd>
                <dd> <a onclick="xShow('密码更改','/account/psw')"><i class="layui-icon layui-icon-password"></i>密码更改</a> </dd>
                <dd> <a class="loginout" href="/sign/out"><i class="layui-icon layui-icon-close"></i>注销</a></dd>
            </dl>
        </li>
    </ul>
</div>
<!-- 顶部结束 -->
<!-- 中部开始 -->
<!-- 左侧菜单开始 -->
<div class="left-nav">
    <div id="side-nav">
        <ul id="nav">
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-senior"></i> <cite>交易管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/tx/paying"> <i class="iconfont">&#xe6a7;</i> <cite>入款中</cite> </a> </li>
                    <li> <a _href="/tx/paid"> <i class="iconfont">&#xe6a7;</i> <cite>入款历史</cite> </a> </li>
                    <li> <a _href="/tx/remitting"> <i class="iconfont">&#xe6a7;</i> <cite>出款中</cite> </a> </li>
                    <li> <a _href="/tx/remitted"> <i class="iconfont">&#xe6a7;</i> <cite>出款历史</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-dollar"></i> <cite>财务管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/fund/flow"> <i class="iconfont">&#xe6a7;</i> <cite>账户资金</cite> </a> </li>
                    <li> <a _href="/fund/statement"> <i class="iconfont">&#xe6a7;</i> <cite>对账单</cite> </a> </li>
                </ul>
            </li>
<!--            <li>-->
<!--                <a href="javascript:;"> <i class="layui-icon layui-icon-chart-screen"></i> <cite>信息统计</cite> <i class="iconfont nav_right">&#xe697;</i> </a>-->
<!--                <ul class="sub-menu">-->
<!--                    <li> <a _href="/stats/pay"> <i class="iconfont">&#xe6a7;</i> <cite>入款统计</cite> </a> </li>-->
<!--                    <li> <a _href="/stats/remit"> <i class="iconfont">&#xe6a7;</i> <cite>代付统计</cite> </a> </li>-->
<!--                </ul>-->
<!--            </li>-->
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-username"></i> <cite>账户设置</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/user/info"> <i class="iconfont">&#xe6a7;</i> <cite>账户信息</cite> </a> </li>
                    <li> <a _href="/user/op"> <i class="iconfont">&#xe6a7;</i> <cite>操作记录</cite> </a> </li>
                    <li> <a _href="/user/password"> <i class="iconfont">&#xe6a7;</i> <cite>密码更改</cite> </a> </li>
                    <li> <a _href="/user/ip"> <i class="iconfont">&#xe6a7;</i> <cite>IP设置</cite> </a> </li>
                </ul>
            </li>

        </ul>
        <ul>
            <li> <a href="/counter" target="_blank"> <i class="layui-icon layui-icon-rmb" ></i> <cite>收银台</cite> </a> </li>
            <li> <a href="//docs.zpay.cc" target="_blank"> <i class="layui-icon layui-icon-fonts-code"></i> <cite>API文档</cite> </a> </li>
        </ul>
    </div>
</div>
<!-- 左侧菜单结束 -->

<!-- 右侧主体开始 -->
<div class="page-content">
    <div class="layui-tab tab" lay-filter="wenav_tab" id="WeTabTip" lay-allowclose="true">
        <ul class="layui-tab-title" id="tabName">
            <li lay-id="1"><i class="layui-icon layui-icon-home"></i></li>
        </ul>
        <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">
                <iframe src='index/welcome' frameborder="0" scrolling="yes" class="xframe"></iframe>
            </div>
        </div>
    </div>
</div>
<!-- 辅助元素，一般用于移动设备下遮罩 -->
<div class="page-content-bg"></div>
<!-- 右侧主体结束 -->
<!-- 中部结束 -->
<!-- 底部开始
<div class="footer">
    <div class="copyright">©2018 支付</div>
</div>
底部结束 -->
<!--Tab菜单右键弹出菜单-->
<ul class="rightMenu" id="rightMenu">
    <li data-type="fresh"><i class="layui-icon layui-icon-refresh text-success"></i> 刷新</li>
    <li data-type="current"><i class="layui-icon layui-icon-close text-danger"></i> 关闭</li>
    <hr class="margin0">
    <li data-type="other"><i class="layui-icon layui-icon-circle-dot text-warning"></i> 关闭其它</li>
    <li data-type="all"><i class="layui-icon layui-icon-close-fill text-danger"></i> 关闭所有</li>
</ul>

<script type="text/javascript" src="/static/layui/layui.js" charset="utf-8"></script>
<script type="text/javascript" src="/static/js/admin.js"></script>
<script type="text/javascript">
    layui.config({
        base: '/static/js/'
        //,version: '101100'
    });
    layui.use(['jquery'], function(){
        const $ = layui.jquery;
        // 模拟登录路由拦截
        $(function(){
            let login = JSON.parse(sessionStorage.getItem("login"));
            if(login == 0){
                window.location.href='/sign';
                return false;
            }else{
                return false;
            }
        })

        // TODO 定时器去获取用户资金, 1分钟秒请求一次
    });

</script>
</body>
</html>