<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<title>欢迎</title>
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<link rel="stylesheet" href="/static/css/font.css">
	<link rel="stylesheet" href="/static/css/style.css">
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
	    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
	<div class="x-body">
		<blockquote class="layui-elem-quote">上次登录IP：<span style="color:#c36969;">192.168.56.1</span></blockquote>
		<div class="layui-row layui-col-space15">
			<div class="layui-col-md4">
				<div class="layui-card">
					<div class="layui-card-header"> 平台入金 <span class="layui-badge layui-bg-blue layuiadmin-badge">日</span> </div>
					<div class="layui-card-body layuiadmin-card-list">
						<p class="layuiadmin-big-font">9,999,666</p>
						<p>平台总入金 <span class="layuiadmin-span-color">88万 <i class="layui-inline layui-icon layui-icon-flag"></i></span> </p>
					</div>
				</div>
			</div>
			<div class="layui-col-md4">
				<div class="layui-card">
					<div class="layui-card-header"> 代理分成 <span class="layui-badge layui-bg-cyan layuiadmin-badge">日</span> </div>
					<div class="layui-card-body layuiadmin-card-list">
						<p class="layuiadmin-big-font">33,555</p>
						<p> 代理总分成 <span class="layuiadmin-span-color">33,555<i class="layui-inline layui-icon layui-icon-dollar"></i></span> </p>
					</div>
				</div>
			</div>
			<div class="layui-col-md4">
				<div class="layui-card">
					<div class="layui-card-header"> 平台分成 <span class="layui-badge layui-bg-green layuiadmin-badge">日</span> </div>
					<div class="layui-card-body layuiadmin-card-list">
						<p class="layuiadmin-big-font">9,999,666</p>
						<p>平台总分成 <span class="layuiadmin-span-color">88万 <i class="layui-inline layui-icon layui-icon-flag"></i></span> </p>
					</div>
				</div>
			</div>
		</div>
		<div class="layui-row layui-col-space15">
			<div class="layui-col-md8">
				<div class="layui-col-md12">
					<div class="layui-card">
						<div class="layui-card-header">数据概览</div>
						<div class="layui-card-body">
							<div class="layui-carousel layadmin-carousel layadmin-dataview" data-anim="fade" lay-filter="LAY-index-dataview">
								<div carousel-item id="LAY-index-dataview">
									<div><i class="layui-icon layui-icon-loading1 layadmin-loading"></i></div>
									<div></div>
									<div></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="layui-col-md4">
				<!-- 待办事项 -->
				<div class="layui-card">
					<div class="layui-card-header">待办事项</div>
					<div class="layui-card-body">
						<div class="layui-carousel layadmin-carousel layadmin-backlog">
							<div carousel-item>
								<ul class="layui-row layui-col-space10">
									<li class="layui-col-xs6">
										<a lay-href="app/content/comment.html" class="layadmin-backlog-body">
											<h3>待审评论</h3>
											<p><cite>66</cite></p>
										</a>
									</li>
									<li class="layui-col-xs6">
										<a lay-href="app/forum/list.html" class="layadmin-backlog-body">
											<h3>待审帖子</h3>
											<p><cite>12</cite></p>
										</a>
									</li>
									<li class="layui-col-xs6">
										<a lay-href="template/goodslist.html" class="layadmin-backlog-body">
											<h3>待审商品</h3>
											<p><cite>99</cite></p>
										</a>
									</li>
									<li class="layui-col-xs6">
										<a href="javascript:;" onclick="layer.tips('不跳转', this, {tips: 3});" class="layadmin-backlog-body">
											<h3>待发货</h3>
											<p><cite>20</cite></p>
										</a>
									</li>
								</ul>
								<ul class="layui-row layui-col-space10">
									<li class="layui-col-xs6">
										<a href="javascript:;" class="layadmin-backlog-body">
											<h3>待审友情链接</h3>
											<p><cite style="color: #FF5722;">5</cite></p>
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
<script src="/static/layui/layui.js"></script>
<script src="/static/js/welcome.js"></script>

</html>