<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>收银台</title>
    <!-- 引入样式 -->
    <link rel="stylesheet" href="./css/element-ui@2.6.1-cashier.css">
    <!-- 引入组件库 -->
    <script src="./js/bank-iconfont.js"></script>
    <script src="./js/vue.min.js"></script>
    <script src="./js/element-ui@2.6.1.js"></script>
</head>

<body>
<div id="wrap">
    <div class="navbox">
        <el-radio-group v-model="pageType">
            <el-radio-button label="wgzf">网关支付</el-radio-button>
            <el-radio-button label="kjzf">快捷支付</el-radio-button>
        </el-radio-group>
    </div>
    <template v-if="pageType === 'wgzf'">
        <div class="wg_Box">
            <el-form ref="wgForm" :model="wgForm" label-width="80px">
                <el-form-item label="金额" class="mw-500" prop="amount" :rules="[{ required: true, message: '请输入金额'}]">
                    <el-input v-model="wgForm.amount" maxl clearable></el-input>
                </el-form-item>
                <el-form-item label="银行" prop="bankType" :rules="[{ required: true, message: '请选择银行'}]">
                    <el-radio-group v-model="wgForm.bankType">
                        <el-radio label="ICBC">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-gongshangyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="ABC">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-nongyeyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="BOC">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-zhongguoyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="CCB">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-jiansheyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="BOCOM">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-jiaotongyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="CMB">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-zhaoshangyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="CITIC">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-zhongxinyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="CMBC">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-zhongguominshengyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="CEB">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-guangdayinhang_huaban"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="PABC">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-pinganyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="SPDB">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-pufayinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="PSBC">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-youzhengchuxu"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="HXB">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-huaxiayinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="CIB">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-xingyeyinhang"></use>
                            </svg>
                        </el-radio>
                        <el-radio label="CGB">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-guangfayinhang"></use>
                            </svg>
                        </el-radio>
                    </el-radio-group>
                </el-form-item>
                <el-form-item class="pt-10">
                    <el-button type="primary" plain class="plr-5" @click="sendwgzf('wgForm')">确定</el-button>
                </el-form-item>
            </el-form>
        </div>
    </template>

    <template v-else>
        <div>
            <template>
                <el-steps :active="activeItem" align-center v-if="!addbank">
                    <el-step title="个人信息" icon="el-icon-edit"></el-step>
                    <el-step title="选择银行卡" icon="el-icon-sort"></el-step>
                    <el-step title="确认支付" icon="el-icon-news"></el-step>
                </el-steps>
                <el-steps :active="activeItem" align-center v-if="addbank">
                    <el-step title="个人信息" icon="el-icon-edit"></el-step>
                    <el-step title="绑定银行卡" icon="el-icon-upload"></el-step>
                    <el-step title="选择银行卡" icon="el-icon-sort"></el-step>
                    <el-step title="确认支付" icon="el-icon-news"></el-step>
                </el-steps>
            </template>
            <template v-if="activeItem==1">
                <div class="_Box">
                    <h1>个人信息</h1>
                    <el-form :model="uinfoForm" ref="uinfoForm" label-width="70px" class="plr-30">
                        <el-form-item label="金额" class="mw-500" prop="amount" :rules="[{ required: true, message: '请输入金额'}]">
                            <el-input v-model="uinfoForm.amount"></el-input>
                        </el-form-item>
                        <el-form-item label="手机号" class="mw-500" prop="uTel" required :rules="[{ required: true, message: '必填'},{ validator: validateTel, trigger: 'blur' }]">
                            <el-input v-model="uinfoForm.uTel" maxlength="11"></el-input>
                        </el-form-item>
                        <el-form-item class="pt-10">
                            <el-button type="primary" plain class="plr-5" @click="sendUinfo('uinfoForm')">确定</el-button>
                        </el-form-item>
                    </el-form>
                </div>
            </template>
            <template v-else-if="(addbank && activeItem==3) || (!addbank && activeItem==2)">
                <div class="_Box">
                    <h1>选择银行卡</h1>
                    <el-form :model="selectCardForm" ref="selectCardForm" label-width="100px" class="plr-30">
                        <el-form-item label="选择银行卡" class="mw-500" prop="num" :rules="[{ required: true, message: '必选'}]">
                            <el-select v-model="selectCardForm.num" placeholder="请选择银行卡">
                                <el-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value"></el-option>
                            </el-select>
                            <el-button type="text" class="addbtn" @click="addbank = true, activeItem = 2, $refs['selectCardForm'].resetFields()">添加银行卡</el-button>
                        </el-form-item>
                        <el-form-item class="pt-10">
                            <el-button type="primary" plain class="plr-5" @click="sendpayCard('selectCardForm')">确定</el-button>
                        </el-form-item>
                    </el-form>
                </div>
            </template>
            <template v-else-if="(addbank && activeItem==4) || (!addbank && activeItem==3)">
                <div class="_Box">
                    <h1>确认支付</h1>
                    <el-form :model="submitPayForm" ref="submitPayForm" label-width="80px" class="plr-30">
                        <el-form-item label="验证码" class="mw-500" prop="code" :rules="[{ required: true, message: '必填'}]">
                            <el-input v-model="submitPayForm.code" placeholder="请输入银行验证码" maxlength="6"></el-input>
                        </el-form-item>
                        <el-form-item>
                            <el-button type="primary" plain class="plr-5" @click="onSubmit('submitPayForm')">立即支付</el-button>
                        </el-form-item>
                    </el-form>
                </div>
            </template>
            <template v-else-if="(addbank && activeItem==2)">
                <div class="_Box">
                    <h1>绑定银行卡</h1>
                    <el-form :model="addCardForm" ref="addCardForm" label-width="95px" class="plr-30 mw-500">
                        <el-form-item label="预留手机号" prop="cardTel" required :rules="[{ required: true, message: '必填'},{ validator: validateTel, trigger: 'blur' }]">
                            <el-input v-model="addCardForm.cardTel" maxlength="11" placeholder="请输入银行卡预留手机号"></el-input>
                        </el-form-item>
                        <el-form-item label="银行卡号" prop="cardNumber" :rules="[{ required: true, message: '必填'}]">
                            <el-input v-model="addCardForm.cardNumber" placeholder="请输入银行卡号"></el-input>
                        </el-form-item>
                        <el-form-item label="开户行" prop="cardBank" :rules="[{ required: true, message: '必填'}]">
                            <el-input v-model="addCardForm.cardBank" placeholder="请输入开户行"></el-input>
                        </el-form-item>
                        <el-form-item label="支行名称" prop="bankBranch" :rules="[{ required: true, message: '必填'}]">
                            <el-input v-model="addCardForm.bankBranch" placeholder="请输入支行名称"></el-input>
                        </el-form-item>
                        <el-form-item label="所属省份" prop="cardProvince" :rules="[{ required: true, message: '必填'}]">
                            <el-input v-model="addCardForm.cardProvince" placeholder="请输入所属省份"></el-input>
                        </el-form-item>
                        <el-form-item label="所属城市" prop="cardCity" :rules="[{ required: true, message: '必填'}]">
                            <el-input v-model="addCardForm.cardCity" placeholder="请输入所属城市"></el-input>
                        </el-form-item>
                        <el-form-item label="持卡人" prop="uName" :rules="[{ required: true, message: '必填'}]">
                            <el-input v-model="addCardForm.uName" placeholder="请输入持卡人姓名"></el-input>
                        </el-form-item>
                        <el-form-item label="身份证号" prop="idCard" :rules="[{ required: true, message: '必填'}]">
                            <el-input v-model="addCardForm.idCard" maxlength="18" placeholder="请输入身份证号"></el-input>
                        </el-form-item>
                        <el-form-item label="业务类型">
                            <el-select v-model="addCardForm.tradeType" disabled placeholder="请选择">
                                <el-option label="对私账户" value="对私账户">
                                </el-option>
                            </el-select>
                        </el-form-item>
                        <el-form-item>
                            <el-button type="primary" plain class="plr-5" @click="addSubmit('addCardForm')">立即添加</el-button>
                            <el-button plain class="plr-5" @click="addbank = false, activeItem = 2, $refs['addCardForm'].resetFields()">取消</el-button>
                        </el-form-item>
                    </el-form>
                </div>
            </template>
        </div>
    </template>

</div>
<script>
	const validateTel = (rule, value, callback) => {
		if (!value) {
			return callback(new Error('请输入手机号'))
		} else if (!(/^1[345678]\d{9}$/.test(value))) {
			callback(new Error('请输入正确的手机号'))
		} else {
			callback()
		}

	}
	new Vue({
		el: '#wrap',
		beforeUpdate() {
			sessionStorage.setItem('pageType', this.pageType)
		},
		data() {
			return {
				pageType: sessionStorage.getItem('pageType') ? sessionStorage.getItem('pageType') : 'wgzf',
				activeItem: sessionStorage.getItem('activeItem') ? sessionStorage.getItem('activeItem') : 1,
				addbank: false,
				options: [{
					value: '12345678901234567890',
					label: '12345678901234567890'
				}, {
					value: '6222021001053295306 ',
					label: '6222021001053295306'
				}],
				wgForm: {
					amount: null,
					bankType: null
				},
				uinfoForm: {
					amount: null,
					uTel: null
				},
				selectCardForm: {
					num: null
				},
				submitPayForm: {
					code: null
				},
				addCardForm: {
					cardTel: null,
					cardNumber: null,
					cardBank: null,
					bankBranch: null,
					cardProvince: null,
					cardCity: null,
					uName: null,
					idCard: null,
					tradeType: '对私账户'
				}
			}
		},
		watch: {
			'wgForm.amount': function (val) {
				this.wgForm.amount = val.replace(/[^\d.]/g, '').replace(/^0[0]+\./, '0.').replace(/^[0]+(\d)/, '$1').replace(
					/^(\-)*(\d+)\.(\d\d).*$/, '$1$2.$3')
			},
			'uinfoForm.amount': function (val) {
				this.uinfoForm.amount = val.replace(/[^\d.]/g, '').replace(/^0[0]+\./, '0.').replace(/^[0]+(\d)/, '$1')
				.replace(
					/^(\-)*(\d+)\.(\d\d).*$/, '$1$2.$3')
			},
			'submitPayForm.code': function (val) {
				this.submitPayForm.code = val.replace(/[^\d.]/g, '')
			},
			'addCardForm.cardNumber': function (val) {
				this.addCardForm.cardNumber = val.replace(/[^\d.]/g, '')
			}
		},
		methods: {
			sendwgzf(formName) {
				this.$refs[formName].validate((valid) => {
					if (valid) {
						console.log('send post')
						callback()
					} else {
						return false;
					}
				})
			},
			sendUinfo(formName) {
				this.$refs[formName].validate((valid) => {
					if (valid) {
						console.log('send post')
						this.activeItem = 2
						sessionStorage.setItem('activeItem', this.activeItem)
					} else {
						return false
					}
				})
			},
			addSubmit(formName) {
				this.$refs[formName].validate((valid) => {
					if (valid) {
						console.log('send post')
						this.activeItem = 3
						sessionStorage.setItem('activeItem', this.activeItem)
					} else {
						return false
					}
				})
			},
			sendpayCard(formName) {
				this.$refs[formName].validate((valid) => {
					if (valid) {
						console.log('send post')
						this.activeItem = this.addbank ? 4 : 3
						sessionStorage.setItem('activeItem', this.activeItem)
					} else {
						return false
					}
				})
			},
			onSubmit(formName) {
				this.$refs[formName].validate((valid) => {
					if (valid) {
						console.log('send post')
					} else {
						return false
					}
				})
			}
		}
	})
</script>
</body>

</html>